apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sharedata1-example
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocfs2-shared
  resources:
    requests:
      storage: 45Gi  # Використовуємо 45Gi з доступних 50Gi (5Gi залишаємо для системи)
  selector:
    matchLabels:
      storage: sharedata1  # Прив'язка до конкретного PV

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sharedata2-example
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocfs2-shared
  resources:
    requests:
      storage: 45Gi  # Використовуємо 45Gi з доступних 50Gi (5Gi залишаємо для системи)
  selector:
    matchLabels:
      storage: sharedata2  # Прив'язка до конкретного PV

