apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sharedata2
  labels:
    type: ocfs2
    storage: sharedata2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany  # OCFS2 підтримує одночасний доступ з кількох нод
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ocfs2-shared
  hostPath:
    path: /sharedata2
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-node
          - work-node

