apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Namespace
  - namespace.yaml
  
  # Node Exporter
  - node-exporter/service.yaml
  - node-exporter/daemonset.yaml
  
  # Kube-state-metrics
  - kube-state-metrics/serviceaccount.yaml
  - kube-state-metrics/clusterrole.yaml
  - kube-state-metrics/clusterrolebinding.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
  
  # Prometheus
  - prometheus/serviceaccount.yaml
  - prometheus/clusterrole.yaml
  - prometheus/clusterrolebinding.yaml
  - prometheus/configmap.yaml
  - prometheus/pvc.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  
  # Grafana
  - grafana/configmap.yaml
  - grafana/configmap-datasources.yaml
  - grafana/secret.yaml
  - grafana/pvc.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/ingressroute.yaml

# Common labels
commonLabels:
  managed-by: kustomize
  part-of: monitoring-stack
