apiVersion: v1
kind: Service
metadata:
  name: portainer-agent
  namespace: portainer-agent
  labels:
    app: portainer-agent
spec:
  type: NodePort
  selector:
    app: portainer-agent
  ports:
  - name: http
    port: 9001
    targetPort: 9001
    protocol: TCP
    nodePort: 30901
