apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-agent
  namespace: portainer-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer-agent
rules:
- apiGroups: [""]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["apps"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portainer-agent
subjects:
- kind: ServiceAccount
  name: portainer-agent
  namespace: portainer-agent
