apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer
  namespace: portainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer
rules:
- apiGroups: [""]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["apps"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - "*"
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portainer
subjects:
- kind: ServiceAccount
  name: portainer
  namespace: portainer
